"use client";

import React, { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

const tokens = {
  dark: {
    bgBase: "#0F0F0F",
    surface: "#181818",
    surfaceRaised: "#1F1F1F",
    textPrimary: "#EAEAEA",
    textSecondary: "#AFAFAF",
    border: "#2A2A2A",
    inputBg: "#141414",
  },
  light: {
    bgBase: "#EAEAEA",
    surface: "#FFFFFF",
    surfaceRaised: "#FFFFFF",
    textPrimary: "#181818",
    textSecondary: "#6B6B6B",
    border: "#D5D5D5",
    inputBg: "#FFFFFF",
  },
  gold: "#B98128",
};

// Maps a requisitions row (joined with customer, line items, and
// order_documents) onto the shape the render logic below expects.
// order_documents rows are only generated by advance_requisition_state
// (migration 0016) as a requisition moves invoiced -> dispatched, so a
// freshly-submitted requisition legitimately has documents: [].
function mapNotification(row) {
  const documents = (row.order_documents || []).map((d) => ({
    id: d.id,
    docType: d.doc_type,
    generatedAt: d.generated_at,
    downloadedAt: d.downloaded_at,
    emailSent: d.email_sent,
    read: d.read_by_brand,
  }));

  return {
    id: row.id,
    invoiceId: row.invoice_id,
    state: row.state,
    submittedAt: row.submitted_at,
    trackingNumber: row.tracking_number,
    declineReason: row.decline_reason,
    customerDisplayName: row.customers?.name ?? "",
    itemNames: (row.requisition_items || []).map((it) => it.products?.name).filter(Boolean),
    documents,
  };
}

const DOC_LABELS = {
  packing_slip: "Packing slip",
  order_form_invoice: "Order form / invoice",
  return_info: "Return info",
};

const STATE_LABELS = {
  submitted: "New request",
  invoiced: "Sent to you",
  confirmed: "Confirmed",
  dispatched: "Dispatched",
  declined: "Declined",
};

const NEXT_ACTION_LABEL = {
  submitted: "Mark as invoiced",
  invoiced: "Mark as confirmed",
  confirmed: "Mark as dispatched",
};

function formatDateTime(iso) {
  if (!iso) return "";
  const d = new Date(iso);
  return (
    d.toLocaleDateString("en-US", { month: "short", day: "numeric" }) +
    " · " +
    d.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" })
  );
}

function itemLabel(names) {
  if (names.length === 0) return "";
  if (names.length <= 2) return names.join(", ");
  return `${names.slice(0, 2).join(", ")} +${names.length - 2} more`;
}

export default function BrandDocumentNotifications() {
  const supabase = createClient();

  const [theme, setTheme] = useState("dark");
  const [notifications, setNotifications] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [loadError, setLoadError] = useState("");
  const [downloadToast, setDownloadToast] = useState(null);

  const [busyId, setBusyId] = useState(null);
  const [actionError, setActionError] = useState({});
  const [trackingDraft, setTrackingDraft] = useState({});
  const [declineDraftId, setDeclineDraftId] = useState(null);
  const [declineReason, setDeclineReason] = useState("");

  const t = tokens[theme];

  async function loadData() {
    const { data, error } = await supabase
      .from("requisitions")
      .select(
        `id, invoice_id, state, submitted_at, tracking_number, decline_reason,
         customers(name),
         requisition_items(id, products(name)),
         order_documents(id, doc_type, generated_at, downloaded_at, email_sent, read_by_brand)`
      )
      .order("submitted_at", { ascending: false });

    if (error) {
      setLoadError(error.message);
    } else {
      setLoadError("");
      setNotifications((data || []).map(mapNotification));
    }
    setIsLoading(false);
  }

  useEffect(() => {
    loadData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const unreadCount = notifications.filter(
    (n) => n.state === "submitted" || n.documents.some((d) => !d.read)
  ).length;

  async function handleDownload(doc, notif) {
    setDownloadToast(`${DOC_LABELS[doc.docType]} downloaded — ${notif.invoiceId}`);
    setTimeout(() => setDownloadToast(null), 1800);

    await supabase
      .from("order_documents")
      .update({ read_by_brand: true, downloaded_at: doc.downloadedAt || new Date().toISOString() })
      .eq("id", doc.id);

    setNotifications((ns) =>
      ns.map((n) =>
        n.id !== notif.id
          ? n
          : {
              ...n,
              documents: n.documents.map((d) =>
                d.id === doc.id ? { ...d, read: true, downloadedAt: d.downloadedAt || new Date().toISOString() } : d
              ),
            }
      )
    );
  }

  async function handleAdvance(notif) {
    setBusyId(notif.id);
    setActionError((e) => ({ ...e, [notif.id]: "" }));

    const isDispatchStep = notif.state === "confirmed";
    const tracking = trackingDraft[notif.id]?.trim();

    if (isDispatchStep && !tracking) {
      setActionError((e) => ({ ...e, [notif.id]: "A tracking number is required to mark this dispatched." }));
      setBusyId(null);
      return;
    }

    const { error } = await supabase.rpc("advance_requisition_state", {
      p_requisition_id: notif.id,
      p_tracking_number: isDispatchStep ? tracking : null,
    });

    if (error) {
      setActionError((e) => ({ ...e, [notif.id]: error.message }));
      setBusyId(null);
      return;
    }

    await loadData();
    setBusyId(null);
  }

  async function handleDecline(notif) {
    if (!declineReason.trim()) {
      setActionError((e) => ({ ...e, [notif.id]: "A reason is required to decline." }));
      return;
    }
    setBusyId(notif.id);
    setActionError((e) => ({ ...e, [notif.id]: "" }));

    const { error } = await supabase.rpc("decline_requisition", {
      p_requisition_id: notif.id,
      p_reason: declineReason.trim(),
    });

    if (error) {
      setActionError((e) => ({ ...e, [notif.id]: error.message }));
      setBusyId(null);
      return;
    }

    setDeclineDraftId(null);
    setDeclineReason("");
    await loadData();
    setBusyId(null);
  }

  const buttonStyle = {
    fontSize: 12,
    fontWeight: 500,
    color: "#0F0F0F",
    background: tokens.gold,
    border: "none",
    borderRadius: 7,
    padding: "7px 13px",
    cursor: "pointer",
    fontFamily: "'Roboto', sans-serif",
  };

  const ghostButtonStyle = {
    fontSize: 12,
    fontWeight: 500,
    color: t.textSecondary,
    background: "transparent",
    border: `1px solid ${t.border}`,
    borderRadius: 7,
    padding: "7px 13px",
    cursor: "pointer",
    fontFamily: "'Roboto', sans-serif",
  };

  return (
    <div
      style={{
        fontFamily: "'Roboto', sans-serif",
        background: t.bgBase,
        minHeight: 640,
        padding: "28px 20px",
        transition: "background 0.2s ease",
      }}
    >
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          marginBottom: 24,
          maxWidth: 760,
          margin: "0 auto 24px auto",
        }}
      >
        <div style={{ display: "flex", alignItems: "baseline", gap: 8 }}>
          <span style={{ fontSize: 18, fontWeight: 700, color: t.textPrimary }}>
            Gift Deck Pro
          </span>
          <span style={{ fontSize: 11, fontWeight: 500, color: t.textSecondary, letterSpacing: "0.03em" }}>
            BRAND PORTAL
          </span>
        </div>
        <button
          onClick={() => setTheme(theme === "dark" ? "light" : "dark")}
          style={{
            fontSize: 11,
            fontWeight: 500,
            color: t.textSecondary,
            background: "transparent",
            border: `1px solid ${t.border}`,
            borderRadius: 6,
            padding: "5px 10px",
            cursor: "pointer",
            fontFamily: "'Roboto', sans-serif",
          }}
        >
          {theme === "dark" ? "Preview: light" : "Preview: dark"}
        </button>
      </div>

      <div style={{ maxWidth: 760, margin: "0 auto" }}>
        <div style={{ marginBottom: 18 }}>
          <div
            style={{ width: 28, height: 3, background: tokens.gold, borderRadius: 2, marginBottom: 12 }}
          />
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <h1 style={{ fontSize: 20, fontWeight: 700, color: t.textPrimary, margin: 0 }}>
              Order documents
            </h1>
            {unreadCount > 0 && (
              <span
                style={{
                  fontSize: 11,
                  fontWeight: 500,
                  color: "#0F0F0F",
                  background: tokens.gold,
                  padding: "2px 9px",
                  borderRadius: 10,
                }}
              >
                {unreadCount} new
              </span>
            )}
          </div>
          <p style={{ fontSize: 13, color: t.textSecondary, margin: "6px 0 0 0", maxWidth: 540 }}>
            Requisitions from your customers, and the packing slips, order forms, and return info
            sheets generated as each one moves through fulfillment.
          </p>
        </div>

        {loadError && (
          <div
            style={{
              background: "rgba(194,71,71,0.12)",
              border: "1px solid rgba(194,71,71,0.4)",
              borderRadius: 8,
              padding: "10px 14px",
              fontSize: 12.5,
              color: "#E27A7A",
              marginBottom: 16,
            }}
          >
            {loadError}
          </div>
        )}

        {isLoading && (
          <div style={{ textAlign: "center", padding: "32px 0", fontSize: 13, color: t.textSecondary }}>
            Loading…
          </div>
        )}

        {!isLoading && notifications.length === 0 && (
          <div
            style={{
              border: `1px dashed ${t.border}`,
              borderRadius: 14,
              padding: "36px 20px",
              textAlign: "center",
            }}
          >
            <p style={{ fontSize: 13, color: t.textSecondary, margin: 0 }}>
              No requisitions yet.
            </p>
          </div>
        )}

        <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
          {notifications.map((n) => {
            const isUnread = n.state === "submitted" || n.documents.some((d) => !d.read);
            const isDeclined = n.state === "declined";
            const nextAction = NEXT_ACTION_LABEL[n.state];
            const isDecliningThis = declineDraftId === n.id;
            const canDecline = n.state === "submitted" || n.state === "invoiced";

            return (
              <div
                key={n.id}
                style={{
                  background: t.surface,
                  border: isDeclined
                    ? "1px solid rgba(194,71,71,0.3)"
                    : isUnread
                    ? `1px solid ${tokens.gold}`
                    : `1px solid ${t.border}`,
                  borderRadius: 12,
                  padding: "16px 18px",
                }}
              >
                <div
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "flex-start",
                    marginBottom: 10,
                  }}
                >
                  <div>
                    <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 3 }}>
                      {isUnread && !isDeclined && (
                        <span
                          style={{
                            width: 7,
                            height: 7,
                            borderRadius: "50%",
                            background: tokens.gold,
                            display: "inline-block",
                          }}
                        />
                      )}
                      <p style={{ fontSize: 14, fontWeight: 500, color: t.textPrimary, margin: 0 }}>
                        {itemLabel(n.itemNames) || "—"}
                      </p>
                    </div>
                    <p style={{ fontSize: 12, color: t.textSecondary, margin: 0 }}>
                      {n.invoiceId} · {n.customerDisplayName} · {formatDateTime(n.submittedAt)}
                    </p>
                  </div>
                  <span
                    style={{
                      fontSize: 11,
                      fontWeight: 500,
                      color: isDeclined ? "#E27A7A" : tokens.gold,
                      background: isDeclined ? "rgba(194,71,71,0.14)" : "rgba(185,129,40,0.14)",
                      padding: "3px 9px",
                      borderRadius: 6,
                      whiteSpace: "nowrap",
                    }}
                  >
                    {STATE_LABELS[n.state]}
                  </span>
                </div>

                {isDeclined && n.declineReason && (
                  <p style={{ fontSize: 12, color: t.textSecondary, margin: "0 0 10px 0" }}>
                    Declined: {n.declineReason}
                  </p>
                )}

                {n.state === "dispatched" && n.trackingNumber && (
                  <p style={{ fontSize: 12, color: t.textSecondary, margin: "0 0 10px 0" }}>
                    Tracking: {n.trackingNumber}
                  </p>
                )}

                {n.documents.length > 0 ? (
                  <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginBottom: canDecline || nextAction ? 12 : 0 }}>
                    {n.documents.map((doc) => (
                      <button
                        key={doc.id}
                        onClick={() => handleDownload(doc, n)}
                        style={{
                          fontSize: 12,
                          fontWeight: 500,
                          color: tokens.gold,
                          background: "transparent",
                          border: `1px solid ${tokens.gold}`,
                          borderRadius: 7,
                          padding: "7px 13px",
                          cursor: "pointer",
                          fontFamily: "'Roboto', sans-serif",
                        }}
                      >
                        ↓ {DOC_LABELS[doc.docType]}
                      </button>
                    ))}
                  </div>
                ) : (
                  !isDeclined && (
                    <p style={{ fontSize: 11.5, color: t.textSecondary, margin: "0 0 12px 0" }}>
                      No documents yet — mark as invoiced to generate the packing slip and order form.
                    </p>
                  )
                )}

                {actionError[n.id] && (
                  <p style={{ fontSize: 11.5, color: "#E27A7A", margin: "0 0 8px 0" }}>
                    {actionError[n.id]}
                  </p>
                )}

                {n.state === "confirmed" && (
                  <input
                    value={trackingDraft[n.id] ?? ""}
                    onChange={(e) => setTrackingDraft((d) => ({ ...d, [n.id]: e.target.value }))}
                    placeholder="Tracking number"
                    style={{
                      fontSize: 12.5,
                      fontFamily: "'Roboto', sans-serif",
                      color: t.textPrimary,
                      background: t.inputBg,
                      border: `1px solid ${t.border}`,
                      borderRadius: 7,
                      padding: "7px 10px",
                      marginBottom: 8,
                      width: "100%",
                      maxWidth: 260,
                      boxSizing: "border-box",
                    }}
                  />
                )}

                {isDecliningThis && (
                  <textarea
                    value={declineReason}
                    onChange={(e) => setDeclineReason(e.target.value)}
                    placeholder="Reason for declining (not shown to the customer)"
                    rows={2}
                    style={{
                      fontSize: 12.5,
                      fontFamily: "'Roboto', sans-serif",
                      color: t.textPrimary,
                      background: t.inputBg,
                      border: `1px solid ${t.border}`,
                      borderRadius: 7,
                      padding: "8px 10px",
                      marginBottom: 8,
                      width: "100%",
                      boxSizing: "border-box",
                      resize: "vertical",
                    }}
                  />
                )}

                {!isDeclined && (
                  <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
                    {nextAction && !isDecliningThis && (
                      <button
                        onClick={() => handleAdvance(n)}
                        disabled={busyId === n.id}
                        style={{ ...buttonStyle, opacity: busyId === n.id ? 0.6 : 1 }}
                      >
                        {busyId === n.id ? "Working…" : nextAction}
                      </button>
                    )}

                    {canDecline && !isDecliningThis && (
                      <button
                        onClick={() => {
                          setDeclineDraftId(n.id);
                          setDeclineReason("");
                          setActionError((e) => ({ ...e, [n.id]: "" }));
                        }}
                        disabled={busyId === n.id}
                        style={ghostButtonStyle}
                      >
                        Decline
                      </button>
                    )}

                    {isDecliningThis && (
                      <>
                        <button
                          onClick={() => handleDecline(n)}
                          disabled={busyId === n.id}
                          style={{ ...buttonStyle, background: "#C24747", opacity: busyId === n.id ? 0.6 : 1 }}
                        >
                          {busyId === n.id ? "Working…" : "Confirm decline"}
                        </button>
                        <button
                          onClick={() => {
                            setDeclineDraftId(null);
                            setDeclineReason("");
                          }}
                          disabled={busyId === n.id}
                          style={ghostButtonStyle}
                        >
                          Cancel
                        </button>
                      </>
                    )}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

      {downloadToast && (
        <div
          style={{
            position: "fixed",
            bottom: 28,
            left: "50%",
            transform: "translateX(-50%)",
            background: t.surfaceRaised,
            border: `1px solid ${tokens.gold}`,
            color: t.textPrimary,
            fontSize: 13,
            fontWeight: 500,
            padding: "10px 18px",
            borderRadius: 8,
            zIndex: 50,
          }}
        >
          {downloadToast}
        </div>
      )}
    </div>
  );
}
